// Code generated by go-swagger; DO NOT EDIT.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"configManager/models"
)

// AddProviderHandlerFunc turns a function with the right signature into a add provider handler
type AddProviderHandlerFunc func(AddProviderParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn AddProviderHandlerFunc) Handle(params AddProviderParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// AddProviderHandler interface for that can handle valid add provider params
type AddProviderHandler interface {
	Handle(AddProviderParams, *models.Customer) middleware.Responder
}

// NewAddProvider creates a new http.Handler for the add provider operation
func NewAddProvider(ctx *middleware.Context, handler AddProviderHandler) *AddProvider {
	return &AddProvider{Context: ctx, Handler: handler}
}

/*AddProvider swagger:route POST /cell/{cell_id}/provider provider addProvider

Add a new provider

*/
type AddProvider struct {
	Context *middleware.Context
	Handler AddProviderHandler
}

func (o *AddProvider) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddProviderParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
