package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// DeleteProviderURL generates an URL for the delete provider operation
type DeleteProviderURL struct {
	CellID     int64
	ProviderID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteProviderURL) WithBasePath(bp string) *DeleteProviderURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteProviderURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteProviderURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/provider/{cell_id}/provider/{provider_id}"

	cellID := swag.FormatInt64(o.CellID)
	if cellID != "" {
		_path = strings.Replace(_path, "{cell_id}", cellID, -1)
	} else {
		return nil, errors.New("CellID is required on DeleteProviderURL")
	}
	providerID := swag.FormatInt64(o.ProviderID)
	if providerID != "" {
		_path = strings.Replace(_path, "{provider_id}", providerID, -1)
	} else {
		return nil, errors.New("ProviderID is required on DeleteProviderURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteProviderURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteProviderURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteProviderURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteProviderURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteProviderURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteProviderURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
