package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../../models"
)

// GetProviderByIDOKCode is the HTTP code returned for type GetProviderByIDOK
const GetProviderByIDOKCode int = 200

/*GetProviderByIDOK successful operation

swagger:response getProviderByIdOK
*/
type GetProviderByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Provider `json:"body,omitempty"`
}

// NewGetProviderByIDOK creates GetProviderByIDOK with default headers values
func NewGetProviderByIDOK() *GetProviderByIDOK {
	return &GetProviderByIDOK{}
}

// WithPayload adds the payload to the get provider by Id o k response
func (o *GetProviderByIDOK) WithPayload(payload *models.Provider) *GetProviderByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get provider by Id o k response
func (o *GetProviderByIDOK) SetPayload(payload *models.Provider) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProviderByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProviderByIDBadRequestCode is the HTTP code returned for type GetProviderByIDBadRequest
const GetProviderByIDBadRequestCode int = 400

/*GetProviderByIDBadRequest Invalid ID supplied

swagger:response getProviderByIdBadRequest
*/
type GetProviderByIDBadRequest struct {
}

// NewGetProviderByIDBadRequest creates GetProviderByIDBadRequest with default headers values
func NewGetProviderByIDBadRequest() *GetProviderByIDBadRequest {
	return &GetProviderByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetProviderByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// GetProviderByIDNotFoundCode is the HTTP code returned for type GetProviderByIDNotFound
const GetProviderByIDNotFoundCode int = 404

/*GetProviderByIDNotFound Provider not found

swagger:response getProviderByIdNotFound
*/
type GetProviderByIDNotFound struct {
}

// NewGetProviderByIDNotFound creates GetProviderByIDNotFound with default headers values
func NewGetProviderByIDNotFound() *GetProviderByIDNotFound {
	return &GetProviderByIDNotFound{}
}

// WriteResponse to the client
func (o *GetProviderByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
