// Code generated by go-swagger; DO NOT EDIT.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// GetProviderOKCode is the HTTP code returned for type GetProviderOK
const GetProviderOKCode int = 200

/*GetProviderOK successful operation

swagger:response getProviderOK
*/
type GetProviderOK struct {

	/*
	  In: Body
	*/
	Payload *models.Provider `json:"body,omitempty"`
}

// NewGetProviderOK creates GetProviderOK with default headers values
func NewGetProviderOK() *GetProviderOK {
	return &GetProviderOK{}
}

// WithPayload adds the payload to the get provider o k response
func (o *GetProviderOK) WithPayload(payload *models.Provider) *GetProviderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get provider o k response
func (o *GetProviderOK) SetPayload(payload *models.Provider) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProviderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProviderBadRequestCode is the HTTP code returned for type GetProviderBadRequest
const GetProviderBadRequestCode int = 400

/*GetProviderBadRequest Invalid ID supplied

swagger:response getProviderBadRequest
*/
type GetProviderBadRequest struct {
}

// NewGetProviderBadRequest creates GetProviderBadRequest with default headers values
func NewGetProviderBadRequest() *GetProviderBadRequest {
	return &GetProviderBadRequest{}
}

// WriteResponse to the client
func (o *GetProviderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetProviderNotFoundCode is the HTTP code returned for type GetProviderNotFound
const GetProviderNotFoundCode int = 404

/*GetProviderNotFound Provider not found

swagger:response getProviderNotFound
*/
type GetProviderNotFound struct {
}

// NewGetProviderNotFound creates GetProviderNotFound with default headers values
func NewGetProviderNotFound() *GetProviderNotFound {
	return &GetProviderNotFound{}
}

// WriteResponse to the client
func (o *GetProviderNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
