// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2016, 2017, 2018 Alexandre Biancalana <ale@biancalanas.net>.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// UpdateProviderOKCode is the HTTP code returned for type UpdateProviderOK
const UpdateProviderOKCode int = 200

/*UpdateProviderOK successful operation

swagger:response updateProviderOK
*/
type UpdateProviderOK struct {
}

// NewUpdateProviderOK creates UpdateProviderOK with default headers values
func NewUpdateProviderOK() *UpdateProviderOK {
	return &UpdateProviderOK{}
}

// WriteResponse to the client
func (o *UpdateProviderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateProviderNotFoundCode is the HTTP code returned for type UpdateProviderNotFound
const UpdateProviderNotFoundCode int = 404

/*UpdateProviderNotFound Does not exists

swagger:response updateProviderNotFound
*/
type UpdateProviderNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateProviderNotFound creates UpdateProviderNotFound with default headers values
func NewUpdateProviderNotFound() *UpdateProviderNotFound {
	return &UpdateProviderNotFound{}
}

// WithPayload adds the payload to the update provider not found response
func (o *UpdateProviderNotFound) WithPayload(payload *models.APIResponse) *UpdateProviderNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update provider not found response
func (o *UpdateProviderNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateProviderNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateProviderConflictCode is the HTTP code returned for type UpdateProviderConflict
const UpdateProviderConflictCode int = 409

/*UpdateProviderConflict Already exists

swagger:response updateProviderConflict
*/
type UpdateProviderConflict struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateProviderConflict creates UpdateProviderConflict with default headers values
func NewUpdateProviderConflict() *UpdateProviderConflict {
	return &UpdateProviderConflict{}
}

// WithPayload adds the payload to the update provider conflict response
func (o *UpdateProviderConflict) WithPayload(payload *models.APIResponse) *UpdateProviderConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update provider conflict response
func (o *UpdateProviderConflict) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateProviderConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateProviderInternalServerErrorCode is the HTTP code returned for type UpdateProviderInternalServerError
const UpdateProviderInternalServerErrorCode int = 500

/*UpdateProviderInternalServerError Internal error

swagger:response updateProviderInternalServerError
*/
type UpdateProviderInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateProviderInternalServerError creates UpdateProviderInternalServerError with default headers values
func NewUpdateProviderInternalServerError() *UpdateProviderInternalServerError {
	return &UpdateProviderInternalServerError{}
}

// WithPayload adds the payload to the update provider internal server error response
func (o *UpdateProviderInternalServerError) WithPayload(payload *models.APIResponse) *UpdateProviderInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update provider internal server error response
func (o *UpdateProviderInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateProviderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
