package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateProviderWithFormParams creates a new UpdateProviderWithFormParams object
// with the default values initialized.
func NewUpdateProviderWithFormParams() UpdateProviderWithFormParams {
	var ()
	return UpdateProviderWithFormParams{}
}

// UpdateProviderWithFormParams contains all the bound params for the update provider with form operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateProviderWithForm
type UpdateProviderWithFormParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*ID of cell that will be used
	  Required: true
	  In: path
	*/
	CellID int64
	/*ID of provider that needs to be updated
	  Required: true
	  In: path
	*/
	ProviderID int64
	/*Updated name of the provider
	  In: formData
	*/
	PublicKey *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateProviderWithFormParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return err
		} else if err := r.ParseForm(); err != nil {
			return err
		}
	}
	fds := runtime.Values(r.Form)

	rCellID, rhkCellID, _ := route.Params.GetOK("cell_id")
	if err := o.bindCellID(rCellID, rhkCellID, route.Formats); err != nil {
		res = append(res, err)
	}

	rProviderID, rhkProviderID, _ := route.Params.GetOK("provider_id")
	if err := o.bindProviderID(rProviderID, rhkProviderID, route.Formats); err != nil {
		res = append(res, err)
	}

	fdPublicKey, fdhkPublicKey, _ := fds.GetOK("public_key")
	if err := o.bindPublicKey(fdPublicKey, fdhkPublicKey, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateProviderWithFormParams) bindCellID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("cell_id", "path", "int64", raw)
	}
	o.CellID = value

	return nil
}

func (o *UpdateProviderWithFormParams) bindProviderID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("provider_id", "path", "int64", raw)
	}
	o.ProviderID = value

	return nil
}

func (o *UpdateProviderWithFormParams) bindPublicKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.PublicKey = &raw

	return nil
}
