// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2016, 2017, 2018 Alexandre Biancalana <ale@biancalanas.net>.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

package loadbalancer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// DeleteCellLoadbalancerRelationshipOKCode is the HTTP code returned for type DeleteCellLoadbalancerRelationshipOK
const DeleteCellLoadbalancerRelationshipOKCode int = 200

/*DeleteCellLoadbalancerRelationshipOK successful operation

swagger:response deleteCellLoadbalancerRelationshipOK
*/
type DeleteCellLoadbalancerRelationshipOK struct {
}

// NewDeleteCellLoadbalancerRelationshipOK creates DeleteCellLoadbalancerRelationshipOK with default headers values
func NewDeleteCellLoadbalancerRelationshipOK() *DeleteCellLoadbalancerRelationshipOK {
	return &DeleteCellLoadbalancerRelationshipOK{}
}

// WriteResponse to the client
func (o *DeleteCellLoadbalancerRelationshipOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteCellLoadbalancerRelationshipNotFoundCode is the HTTP code returned for type DeleteCellLoadbalancerRelationshipNotFound
const DeleteCellLoadbalancerRelationshipNotFoundCode int = 404

/*DeleteCellLoadbalancerRelationshipNotFound loadbalancer or entity not found

swagger:response deleteCellLoadbalancerRelationshipNotFound
*/
type DeleteCellLoadbalancerRelationshipNotFound struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewDeleteCellLoadbalancerRelationshipNotFound creates DeleteCellLoadbalancerRelationshipNotFound with default headers values
func NewDeleteCellLoadbalancerRelationshipNotFound() *DeleteCellLoadbalancerRelationshipNotFound {
	return &DeleteCellLoadbalancerRelationshipNotFound{}
}

// WithPayload adds the payload to the delete cell loadbalancer relationship not found response
func (o *DeleteCellLoadbalancerRelationshipNotFound) WithPayload(payload models.APIResponse) *DeleteCellLoadbalancerRelationshipNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cell loadbalancer relationship not found response
func (o *DeleteCellLoadbalancerRelationshipNotFound) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCellLoadbalancerRelationshipNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DeleteCellLoadbalancerRelationshipInternalServerErrorCode is the HTTP code returned for type DeleteCellLoadbalancerRelationshipInternalServerError
const DeleteCellLoadbalancerRelationshipInternalServerErrorCode int = 500

/*DeleteCellLoadbalancerRelationshipInternalServerError Internal error

swagger:response deleteCellLoadbalancerRelationshipInternalServerError
*/
type DeleteCellLoadbalancerRelationshipInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewDeleteCellLoadbalancerRelationshipInternalServerError creates DeleteCellLoadbalancerRelationshipInternalServerError with default headers values
func NewDeleteCellLoadbalancerRelationshipInternalServerError() *DeleteCellLoadbalancerRelationshipInternalServerError {
	return &DeleteCellLoadbalancerRelationshipInternalServerError{}
}

// WithPayload adds the payload to the delete cell loadbalancer relationship internal server error response
func (o *DeleteCellLoadbalancerRelationshipInternalServerError) WithPayload(payload models.APIResponse) *DeleteCellLoadbalancerRelationshipInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cell loadbalancer relationship internal server error response
func (o *DeleteCellLoadbalancerRelationshipInternalServerError) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCellLoadbalancerRelationshipInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
