// Code generated by go-swagger; DO NOT EDIT.

package keypair

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"configManager/models"
)

// AddCellKeypairHandlerFunc turns a function with the right signature into a add cell keypair handler
type AddCellKeypairHandlerFunc func(AddCellKeypairParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn AddCellKeypairHandlerFunc) Handle(params AddCellKeypairParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// AddCellKeypairHandler interface for that can handle valid add cell keypair params
type AddCellKeypairHandler interface {
	Handle(AddCellKeypairParams, *models.Customer) middleware.Responder
}

// NewAddCellKeypair creates a new http.Handler for the add cell keypair operation
func NewAddCellKeypair(ctx *middleware.Context, handler AddCellKeypairHandler) *AddCellKeypair {
	return &AddCellKeypair{Context: ctx, Handler: handler}
}

/*AddCellKeypair swagger:route POST /cell/{cell_id}/keypair/{keypair_name} keypair addCellKeypair

Add a keypair to cell

*/
type AddCellKeypair struct {
	Context *middleware.Context
	Handler AddCellKeypairHandler
}

func (o *AddCellKeypair) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddCellKeypairParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
