package keypair

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewFindKeypairByCustomerParams creates a new FindKeypairByCustomerParams object
// with the default values initialized.
func NewFindKeypairByCustomerParams() FindKeypairByCustomerParams {
	var ()
	return FindKeypairByCustomerParams{}
}

// FindKeypairByCustomerParams contains all the bound params for the find keypair by customer operation
// typically these are obtained from a http.Request
//
// swagger:parameters findKeypairByCustomer
type FindKeypairByCustomerParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindKeypairByCustomerParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
