// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2016, 2017, 2018 Alexandre Biancalana <ale@biancalanas.net>.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

package keypair

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// FindKeypairByCustomerOKCode is the HTTP code returned for type FindKeypairByCustomerOK
const FindKeypairByCustomerOKCode int = 200

/*FindKeypairByCustomerOK successful operation

swagger:response findKeypairByCustomerOK
*/
type FindKeypairByCustomerOK struct {

	/*
	  In: Body
	*/
	Payload models.FindKeypairByCustomerOKBody `json:"body,omitempty"`
}

// NewFindKeypairByCustomerOK creates FindKeypairByCustomerOK with default headers values
func NewFindKeypairByCustomerOK() *FindKeypairByCustomerOK {
	return &FindKeypairByCustomerOK{}
}

// WithPayload adds the payload to the find keypair by customer o k response
func (o *FindKeypairByCustomerOK) WithPayload(payload models.FindKeypairByCustomerOKBody) *FindKeypairByCustomerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find keypair by customer o k response
func (o *FindKeypairByCustomerOK) SetPayload(payload models.FindKeypairByCustomerOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindKeypairByCustomerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.FindKeypairByCustomerOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// FindKeypairByCustomerBadRequestCode is the HTTP code returned for type FindKeypairByCustomerBadRequest
const FindKeypairByCustomerBadRequestCode int = 400

/*FindKeypairByCustomerBadRequest Invalid customer id

swagger:response findKeypairByCustomerBadRequest
*/
type FindKeypairByCustomerBadRequest struct {
}

// NewFindKeypairByCustomerBadRequest creates FindKeypairByCustomerBadRequest with default headers values
func NewFindKeypairByCustomerBadRequest() *FindKeypairByCustomerBadRequest {
	return &FindKeypairByCustomerBadRequest{}
}

// WriteResponse to the client
func (o *FindKeypairByCustomerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// FindKeypairByCustomerNotFoundCode is the HTTP code returned for type FindKeypairByCustomerNotFound
const FindKeypairByCustomerNotFoundCode int = 404

/*FindKeypairByCustomerNotFound Keypair not found

swagger:response findKeypairByCustomerNotFound
*/
type FindKeypairByCustomerNotFound struct {
}

// NewFindKeypairByCustomerNotFound creates FindKeypairByCustomerNotFound with default headers values
func NewFindKeypairByCustomerNotFound() *FindKeypairByCustomerNotFound {
	return &FindKeypairByCustomerNotFound{}
}

// WriteResponse to the client
func (o *FindKeypairByCustomerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// FindKeypairByCustomerInternalServerErrorCode is the HTTP code returned for type FindKeypairByCustomerInternalServerError
const FindKeypairByCustomerInternalServerErrorCode int = 500

/*FindKeypairByCustomerInternalServerError InternalError

swagger:response findKeypairByCustomerInternalServerError
*/
type FindKeypairByCustomerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewFindKeypairByCustomerInternalServerError creates FindKeypairByCustomerInternalServerError with default headers values
func NewFindKeypairByCustomerInternalServerError() *FindKeypairByCustomerInternalServerError {
	return &FindKeypairByCustomerInternalServerError{}
}

// WithPayload adds the payload to the find keypair by customer internal server error response
func (o *FindKeypairByCustomerInternalServerError) WithPayload(payload *models.APIResponse) *FindKeypairByCustomerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find keypair by customer internal server error response
func (o *FindKeypairByCustomerInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindKeypairByCustomerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
