// Code generated by go-swagger; DO NOT EDIT.

package keypair

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"configManager/models"
)

// GetKeypairByIDHandlerFunc turns a function with the right signature into a get keypair by Id handler
type GetKeypairByIDHandlerFunc func(GetKeypairByIDParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn GetKeypairByIDHandlerFunc) Handle(params GetKeypairByIDParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// GetKeypairByIDHandler interface for that can handle valid get keypair by Id params
type GetKeypairByIDHandler interface {
	Handle(GetKeypairByIDParams, *models.Customer) middleware.Responder
}

// NewGetKeypairByID creates a new http.Handler for the get keypair by Id operation
func NewGetKeypairByID(ctx *middleware.Context, handler GetKeypairByIDHandler) *GetKeypairByID {
	return &GetKeypairByID{Context: ctx, Handler: handler}
}

/*GetKeypairByID swagger:route GET /keypair/{keypair_id} keypair getKeypairById

Find keypair by ID

Returns a single keypair

*/
type GetKeypairByID struct {
	Context *middleware.Context
	Handler GetKeypairByIDHandler
}

func (o *GetKeypairByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetKeypairByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
