// Code generated by go-swagger; DO NOT EDIT.

package keypair

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"configManager/models"
)

// UpdateKeypairHandlerFunc turns a function with the right signature into a update keypair handler
type UpdateKeypairHandlerFunc func(UpdateKeypairParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateKeypairHandlerFunc) Handle(params UpdateKeypairParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// UpdateKeypairHandler interface for that can handle valid update keypair params
type UpdateKeypairHandler interface {
	Handle(UpdateKeypairParams, *models.Customer) middleware.Responder
}

// NewUpdateKeypair creates a new http.Handler for the update keypair operation
func NewUpdateKeypair(ctx *middleware.Context, handler UpdateKeypairHandler) *UpdateKeypair {
	return &UpdateKeypair{Context: ctx, Handler: handler}
}

/*UpdateKeypair swagger:route PUT /keypair keypair updateKeypair

Update an existing keypair

*/
type UpdateKeypair struct {
	Context *middleware.Context
	Handler UpdateKeypairHandler
}

func (o *UpdateKeypair) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateKeypairParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
