db:
  Host: 192.168.20.54
providers:
  AWS:
    us-east-1:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      - us-east-1e
    us-east-2:
      - us-east-2a
      - us-east-2b
      - us-east-2c
    us-west-1:
      - us-west-1a
      - us-west-1c
    us-west-2:
      - us-west-2a
      - us-west-2b
      - us-west-2c
    sa-east-1:
      - sa-east-1a
      - sa-east-1b
      - sa-east-1c
  GCP:
    us-west1:
      - us-west1-a
      - us-west1-b
      - us-west1-c
    us-central1:
      - us-central1-a
      - us-central1-b
      - us-central1-c
      - us-central1-f
