package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../../models"
)

// AddCellHostCreatedCode is the HTTP code returned for type AddCellHostCreated
const AddCellHostCreatedCode int = 201

/*AddCellHostCreated Created

swagger:response addCellHostCreated
*/
type AddCellHostCreated struct {

	/*
	  In: Body
	*/
	Payload int64 `json:"body,omitempty"`
}

// NewAddCellHostCreated creates AddCellHostCreated with default headers values
func NewAddCellHostCreated() *AddCellHostCreated {
	return &AddCellHostCreated{}
}

// WithPayload adds the payload to the add cell host created response
func (o *AddCellHostCreated) WithPayload(payload int64) *AddCellHostCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add cell host created response
func (o *AddCellHostCreated) SetPayload(payload int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCellHostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// AddCellHostMethodNotAllowedCode is the HTTP code returned for type AddCellHostMethodNotAllowed
const AddCellHostMethodNotAllowedCode int = 405

/*AddCellHostMethodNotAllowed Invalid input

swagger:response addCellHostMethodNotAllowed
*/
type AddCellHostMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewAddCellHostMethodNotAllowed creates AddCellHostMethodNotAllowed with default headers values
func NewAddCellHostMethodNotAllowed() *AddCellHostMethodNotAllowed {
	return &AddCellHostMethodNotAllowed{}
}

// WithPayload adds the payload to the add cell host method not allowed response
func (o *AddCellHostMethodNotAllowed) WithPayload(payload models.APIResponse) *AddCellHostMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add cell host method not allowed response
func (o *AddCellHostMethodNotAllowed) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCellHostMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// AddCellHostConflictCode is the HTTP code returned for type AddCellHostConflict
const AddCellHostConflictCode int = 409

/*AddCellHostConflict Already exists

swagger:response addCellHostConflict
*/
type AddCellHostConflict struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewAddCellHostConflict creates AddCellHostConflict with default headers values
func NewAddCellHostConflict() *AddCellHostConflict {
	return &AddCellHostConflict{}
}

// WithPayload adds the payload to the add cell host conflict response
func (o *AddCellHostConflict) WithPayload(payload models.APIResponse) *AddCellHostConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add cell host conflict response
func (o *AddCellHostConflict) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCellHostConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// AddCellHostInternalServerErrorCode is the HTTP code returned for type AddCellHostInternalServerError
const AddCellHostInternalServerErrorCode int = 500

/*AddCellHostInternalServerError Internal error

swagger:response addCellHostInternalServerError
*/
type AddCellHostInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewAddCellHostInternalServerError creates AddCellHostInternalServerError with default headers values
func NewAddCellHostInternalServerError() *AddCellHostInternalServerError {
	return &AddCellHostInternalServerError{}
}

// WithPayload adds the payload to the add cell host internal server error response
func (o *AddCellHostInternalServerError) WithPayload(payload models.APIResponse) *AddCellHostInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add cell host internal server error response
func (o *AddCellHostInternalServerError) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddCellHostInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
