// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2016, 2017, 2018 Alexandre Biancalana <ale@biancalanas.net>.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

package router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// DeleteCellRouterOKCode is the HTTP code returned for type DeleteCellRouterOK
const DeleteCellRouterOKCode int = 200

/*DeleteCellRouterOK successful operation

swagger:response deleteCellRouterOK
*/
type DeleteCellRouterOK struct {

	/*
	  In: Body
	*/
	Payload *models.Router `json:"body,omitempty"`
}

// NewDeleteCellRouterOK creates DeleteCellRouterOK with default headers values
func NewDeleteCellRouterOK() *DeleteCellRouterOK {
	return &DeleteCellRouterOK{}
}

// WithPayload adds the payload to the delete cell router o k response
func (o *DeleteCellRouterOK) WithPayload(payload *models.Router) *DeleteCellRouterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cell router o k response
func (o *DeleteCellRouterOK) SetPayload(payload *models.Router) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCellRouterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteCellRouterBadRequestCode is the HTTP code returned for type DeleteCellRouterBadRequest
const DeleteCellRouterBadRequestCode int = 400

/*DeleteCellRouterBadRequest Invalid cell id or router id

swagger:response deleteCellRouterBadRequest
*/
type DeleteCellRouterBadRequest struct {
}

// NewDeleteCellRouterBadRequest creates DeleteCellRouterBadRequest with default headers values
func NewDeleteCellRouterBadRequest() *DeleteCellRouterBadRequest {
	return &DeleteCellRouterBadRequest{}
}

// WriteResponse to the client
func (o *DeleteCellRouterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteCellRouterNotFoundCode is the HTTP code returned for type DeleteCellRouterNotFound
const DeleteCellRouterNotFoundCode int = 404

/*DeleteCellRouterNotFound router not found

swagger:response deleteCellRouterNotFound
*/
type DeleteCellRouterNotFound struct {
}

// NewDeleteCellRouterNotFound creates DeleteCellRouterNotFound with default headers values
func NewDeleteCellRouterNotFound() *DeleteCellRouterNotFound {
	return &DeleteCellRouterNotFound{}
}

// WriteResponse to the client
func (o *DeleteCellRouterNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteCellRouterInternalServerErrorCode is the HTTP code returned for type DeleteCellRouterInternalServerError
const DeleteCellRouterInternalServerErrorCode int = 500

/*DeleteCellRouterInternalServerError Internal error

swagger:response deleteCellRouterInternalServerError
*/
type DeleteCellRouterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteCellRouterInternalServerError creates DeleteCellRouterInternalServerError with default headers values
func NewDeleteCellRouterInternalServerError() *DeleteCellRouterInternalServerError {
	return &DeleteCellRouterInternalServerError{}
}

// WithPayload adds the payload to the delete cell router internal server error response
func (o *DeleteCellRouterInternalServerError) WithPayload(payload *models.APIResponse) *DeleteCellRouterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cell router internal server error response
func (o *DeleteCellRouterInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCellRouterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
