package component

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"../../../models"
)

// AddComponentHandlerFunc turns a function with the right signature into a add component handler
type AddComponentHandlerFunc func(AddComponentParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn AddComponentHandlerFunc) Handle(params AddComponentParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// AddComponentHandler interface for that can handle valid add component params
type AddComponentHandler interface {
	Handle(AddComponentParams, *models.Customer) middleware.Responder
}

// NewAddComponent creates a new http.Handler for the add component operation
func NewAddComponent(ctx *middleware.Context, handler AddComponentHandler) *AddComponent {
	return &AddComponent{Context: ctx, Handler: handler}
}

/*AddComponent swagger:route POST /cell/{cell_id}/component component addComponent

Add a new component

*/
type AddComponent struct {
	Context *middleware.Context
	Handler AddComponentHandler
}

func (o *AddComponent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddComponentParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
