// Code generated by go-swagger; DO NOT EDIT.

package component

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"configManager/models"
)

// GetCellComponentHandlerFunc turns a function with the right signature into a get cell component handler
type GetCellComponentHandlerFunc func(GetCellComponentParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCellComponentHandlerFunc) Handle(params GetCellComponentParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// GetCellComponentHandler interface for that can handle valid get cell component params
type GetCellComponentHandler interface {
	Handle(GetCellComponentParams, *models.Customer) middleware.Responder
}

// NewGetCellComponent creates a new http.Handler for the get cell component operation
func NewGetCellComponent(ctx *middleware.Context, handler GetCellComponentHandler) *GetCellComponent {
	return &GetCellComponent{Context: ctx, Handler: handler}
}

/*GetCellComponent swagger:route GET /cell/{cell_id}/component/{component_id} component getCellComponent

Get Component

*/
type GetCellComponent struct {
	Context *middleware.Context
	Handler GetCellComponentHandler
}

func (o *GetCellComponent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCellComponentParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
