// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2016, 2017, 2018 Alexandre Biancalana <ale@biancalanas.net>.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

package component

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// GetCellComponentOKCode is the HTTP code returned for type GetCellComponentOK
const GetCellComponentOKCode int = 200

/*GetCellComponentOK successful operation

swagger:response getCellComponentOK
*/
type GetCellComponentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Component `json:"body,omitempty"`
}

// NewGetCellComponentOK creates GetCellComponentOK with default headers values
func NewGetCellComponentOK() *GetCellComponentOK {
	return &GetCellComponentOK{}
}

// WithPayload adds the payload to the get cell component o k response
func (o *GetCellComponentOK) WithPayload(payload *models.Component) *GetCellComponentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cell component o k response
func (o *GetCellComponentOK) SetPayload(payload *models.Component) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCellComponentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCellComponentBadRequestCode is the HTTP code returned for type GetCellComponentBadRequest
const GetCellComponentBadRequestCode int = 400

/*GetCellComponentBadRequest Invalid cell id or component id

swagger:response getCellComponentBadRequest
*/
type GetCellComponentBadRequest struct {
}

// NewGetCellComponentBadRequest creates GetCellComponentBadRequest with default headers values
func NewGetCellComponentBadRequest() *GetCellComponentBadRequest {
	return &GetCellComponentBadRequest{}
}

// WriteResponse to the client
func (o *GetCellComponentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetCellComponentNotFoundCode is the HTTP code returned for type GetCellComponentNotFound
const GetCellComponentNotFoundCode int = 404

/*GetCellComponentNotFound component not found

swagger:response getCellComponentNotFound
*/
type GetCellComponentNotFound struct {
}

// NewGetCellComponentNotFound creates GetCellComponentNotFound with default headers values
func NewGetCellComponentNotFound() *GetCellComponentNotFound {
	return &GetCellComponentNotFound{}
}

// WriteResponse to the client
func (o *GetCellComponentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetCellComponentInternalServerErrorCode is the HTTP code returned for type GetCellComponentInternalServerError
const GetCellComponentInternalServerErrorCode int = 500

/*GetCellComponentInternalServerError Internal error

swagger:response getCellComponentInternalServerError
*/
type GetCellComponentInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetCellComponentInternalServerError creates GetCellComponentInternalServerError with default headers values
func NewGetCellComponentInternalServerError() *GetCellComponentInternalServerError {
	return &GetCellComponentInternalServerError{}
}

// WithPayload adds the payload to the get cell component internal server error response
func (o *GetCellComponentInternalServerError) WithPayload(payload *models.APIResponse) *GetCellComponentInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cell component internal server error response
func (o *GetCellComponentInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCellComponentInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
