package cell

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteCellBadRequestCode is the HTTP code returned for type DeleteCellBadRequest
const DeleteCellBadRequestCode int = 400

/*DeleteCellBadRequest Invalid ID supplied

swagger:response deleteCellBadRequest
*/
type DeleteCellBadRequest struct {
}

// NewDeleteCellBadRequest creates DeleteCellBadRequest with default headers values
func NewDeleteCellBadRequest() *DeleteCellBadRequest {
	return &DeleteCellBadRequest{}
}

// WriteResponse to the client
func (o *DeleteCellBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// DeleteCellNotFoundCode is the HTTP code returned for type DeleteCellNotFound
const DeleteCellNotFoundCode int = 404

/*DeleteCellNotFound Cell not found

swagger:response deleteCellNotFound
*/
type DeleteCellNotFound struct {
}

// NewDeleteCellNotFound creates DeleteCellNotFound with default headers values
func NewDeleteCellNotFound() *DeleteCellNotFound {
	return &DeleteCellNotFound{}
}

// WriteResponse to the client
func (o *DeleteCellNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
