package cell

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"../../../models"
)

// DeployCellByIDHandlerFunc turns a function with the right signature into a deploy cell by Id handler
type DeployCellByIDHandlerFunc func(DeployCellByIDParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn DeployCellByIDHandlerFunc) Handle(params DeployCellByIDParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// DeployCellByIDHandler interface for that can handle valid deploy cell by Id params
type DeployCellByIDHandler interface {
	Handle(DeployCellByIDParams, *models.Customer) middleware.Responder
}

// NewDeployCellByID creates a new http.Handler for the deploy cell by Id operation
func NewDeployCellByID(ctx *middleware.Context, handler DeployCellByIDHandler) *DeployCellByID {
	return &DeployCellByID{Context: ctx, Handler: handler}
}

/*DeployCellByID swagger:route GET /cell/{cell_id}/deploy cell deployCellById

Deploy cell by ID

Deploy a single cell

*/
type DeployCellByID struct {
	Context *middleware.Context
	Handler DeployCellByIDHandler
}

func (o *DeployCellByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeployCellByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
