// Code generated by go-swagger; DO NOT EDIT.

package cell

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// FindCellByCustomerOKCode is the HTTP code returned for type FindCellByCustomerOK
const FindCellByCustomerOKCode int = 200

/*FindCellByCustomerOK successful operation

swagger:response findCellByCustomerOK
*/
type FindCellByCustomerOK struct {

	/*
	  In: Body
	*/
	Payload models.FindCellByCustomerOKBody `json:"body,omitempty"`
}

// NewFindCellByCustomerOK creates FindCellByCustomerOK with default headers values
func NewFindCellByCustomerOK() *FindCellByCustomerOK {
	return &FindCellByCustomerOK{}
}

// WithPayload adds the payload to the find cell by customer o k response
func (o *FindCellByCustomerOK) WithPayload(payload models.FindCellByCustomerOKBody) *FindCellByCustomerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find cell by customer o k response
func (o *FindCellByCustomerOK) SetPayload(payload models.FindCellByCustomerOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindCellByCustomerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.FindCellByCustomerOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// FindCellByCustomerBadRequestCode is the HTTP code returned for type FindCellByCustomerBadRequest
const FindCellByCustomerBadRequestCode int = 400

/*FindCellByCustomerBadRequest Invalid cell name

swagger:response findCellByCustomerBadRequest
*/
type FindCellByCustomerBadRequest struct {
}

// NewFindCellByCustomerBadRequest creates FindCellByCustomerBadRequest with default headers values
func NewFindCellByCustomerBadRequest() *FindCellByCustomerBadRequest {
	return &FindCellByCustomerBadRequest{}
}

// WriteResponse to the client
func (o *FindCellByCustomerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// FindCellByCustomerNotFoundCode is the HTTP code returned for type FindCellByCustomerNotFound
const FindCellByCustomerNotFoundCode int = 404

/*FindCellByCustomerNotFound cells not found

swagger:response findCellByCustomerNotFound
*/
type FindCellByCustomerNotFound struct {
}

// NewFindCellByCustomerNotFound creates FindCellByCustomerNotFound with default headers values
func NewFindCellByCustomerNotFound() *FindCellByCustomerNotFound {
	return &FindCellByCustomerNotFound{}
}

// WriteResponse to the client
func (o *FindCellByCustomerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// FindCellByCustomerInternalServerErrorCode is the HTTP code returned for type FindCellByCustomerInternalServerError
const FindCellByCustomerInternalServerErrorCode int = 500

/*FindCellByCustomerInternalServerError Internal error

swagger:response findCellByCustomerInternalServerError
*/
type FindCellByCustomerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewFindCellByCustomerInternalServerError creates FindCellByCustomerInternalServerError with default headers values
func NewFindCellByCustomerInternalServerError() *FindCellByCustomerInternalServerError {
	return &FindCellByCustomerInternalServerError{}
}

// WithPayload adds the payload to the find cell by customer internal server error response
func (o *FindCellByCustomerInternalServerError) WithPayload(payload models.APIResponse) *FindCellByCustomerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find cell by customer internal server error response
func (o *FindCellByCustomerInternalServerError) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindCellByCustomerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
