// Code generated by go-swagger; DO NOT EDIT.

package cell

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"configManager/models"
)

// FindCellByCustomerHandlerFunc turns a function with the right signature into a find cell by customer handler
type FindCellByCustomerHandlerFunc func(FindCellByCustomerParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn FindCellByCustomerHandlerFunc) Handle(params FindCellByCustomerParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// FindCellByCustomerHandler interface for that can handle valid find cell by customer params
type FindCellByCustomerHandler interface {
	Handle(FindCellByCustomerParams, *models.Customer) middleware.Responder
}

// NewFindCellByCustomer creates a new http.Handler for the find cell by customer operation
func NewFindCellByCustomer(ctx *middleware.Context, handler FindCellByCustomerHandler) *FindCellByCustomer {
	return &FindCellByCustomer{Context: ctx, Handler: handler}
}

/*FindCellByCustomer swagger:route GET /cells cell findCellByCustomer

Finds Cells by customer

*/
type FindCellByCustomer struct {
	Context *middleware.Context
	Handler FindCellByCustomerHandler
}

func (o *FindCellByCustomer) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindCellByCustomerParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
