// Code generated by go-swagger; DO NOT EDIT.

package cell

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"configManager/models"
)

// UpdateCellWithFormHandlerFunc turns a function with the right signature into a update cell with form handler
type UpdateCellWithFormHandlerFunc func(UpdateCellWithFormParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateCellWithFormHandlerFunc) Handle(params UpdateCellWithFormParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// UpdateCellWithFormHandler interface for that can handle valid update cell with form params
type UpdateCellWithFormHandler interface {
	Handle(UpdateCellWithFormParams, *models.Customer) middleware.Responder
}

// NewUpdateCellWithForm creates a new http.Handler for the update cell with form operation
func NewUpdateCellWithForm(ctx *middleware.Context, handler UpdateCellWithFormHandler) *UpdateCellWithForm {
	return &UpdateCellWithForm{Context: ctx, Handler: handler}
}

/*UpdateCellWithForm swagger:route POST /cell/{cell_id} cell updateCellWithForm

Updates a cell with form data

*/
type UpdateCellWithForm struct {
	Context *middleware.Context
	Handler UpdateCellWithFormHandler
}

func (o *UpdateCellWithForm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateCellWithFormParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
