package cell

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateCellWithFormMethodNotAllowedCode is the HTTP code returned for type UpdateCellWithFormMethodNotAllowed
const UpdateCellWithFormMethodNotAllowedCode int = 405

/*UpdateCellWithFormMethodNotAllowed Invalid input

swagger:response updateCellWithFormMethodNotAllowed
*/
type UpdateCellWithFormMethodNotAllowed struct {
}

// NewUpdateCellWithFormMethodNotAllowed creates UpdateCellWithFormMethodNotAllowed with default headers values
func NewUpdateCellWithFormMethodNotAllowed() *UpdateCellWithFormMethodNotAllowed {
	return &UpdateCellWithFormMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateCellWithFormMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
}
