// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2016, 2017, 2018 Alexandre Biancalana <ale@biancalanas.net>.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

package hostgroup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// ConnectHostgroupToNetworkOKCode is the HTTP code returned for type ConnectHostgroupToNetworkOK
const ConnectHostgroupToNetworkOKCode int = 200

/*ConnectHostgroupToNetworkOK successful operation

swagger:response connectHostgroupToNetworkOK
*/
type ConnectHostgroupToNetworkOK struct {
}

// NewConnectHostgroupToNetworkOK creates ConnectHostgroupToNetworkOK with default headers values
func NewConnectHostgroupToNetworkOK() *ConnectHostgroupToNetworkOK {
	return &ConnectHostgroupToNetworkOK{}
}

// WriteResponse to the client
func (o *ConnectHostgroupToNetworkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// ConnectHostgroupToNetworkBadRequestCode is the HTTP code returned for type ConnectHostgroupToNetworkBadRequest
const ConnectHostgroupToNetworkBadRequestCode int = 400

/*ConnectHostgroupToNetworkBadRequest Invalid cell id or role id

swagger:response connectHostgroupToNetworkBadRequest
*/
type ConnectHostgroupToNetworkBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewConnectHostgroupToNetworkBadRequest creates ConnectHostgroupToNetworkBadRequest with default headers values
func NewConnectHostgroupToNetworkBadRequest() *ConnectHostgroupToNetworkBadRequest {
	return &ConnectHostgroupToNetworkBadRequest{}
}

// WithPayload adds the payload to the connect hostgroup to network bad request response
func (o *ConnectHostgroupToNetworkBadRequest) WithPayload(payload *models.APIResponse) *ConnectHostgroupToNetworkBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the connect hostgroup to network bad request response
func (o *ConnectHostgroupToNetworkBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConnectHostgroupToNetworkBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ConnectHostgroupToNetworkNotFoundCode is the HTTP code returned for type ConnectHostgroupToNetworkNotFound
const ConnectHostgroupToNetworkNotFoundCode int = 404

/*ConnectHostgroupToNetworkNotFound Hostgroup does not exists

swagger:response connectHostgroupToNetworkNotFound
*/
type ConnectHostgroupToNetworkNotFound struct {
}

// NewConnectHostgroupToNetworkNotFound creates ConnectHostgroupToNetworkNotFound with default headers values
func NewConnectHostgroupToNetworkNotFound() *ConnectHostgroupToNetworkNotFound {
	return &ConnectHostgroupToNetworkNotFound{}
}

// WriteResponse to the client
func (o *ConnectHostgroupToNetworkNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ConnectHostgroupToNetworkInternalServerErrorCode is the HTTP code returned for type ConnectHostgroupToNetworkInternalServerError
const ConnectHostgroupToNetworkInternalServerErrorCode int = 500

/*ConnectHostgroupToNetworkInternalServerError Internal error

swagger:response connectHostgroupToNetworkInternalServerError
*/
type ConnectHostgroupToNetworkInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewConnectHostgroupToNetworkInternalServerError creates ConnectHostgroupToNetworkInternalServerError with default headers values
func NewConnectHostgroupToNetworkInternalServerError() *ConnectHostgroupToNetworkInternalServerError {
	return &ConnectHostgroupToNetworkInternalServerError{}
}

// WithPayload adds the payload to the connect hostgroup to network internal server error response
func (o *ConnectHostgroupToNetworkInternalServerError) WithPayload(payload *models.APIResponse) *ConnectHostgroupToNetworkInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the connect hostgroup to network internal server error response
func (o *ConnectHostgroupToNetworkInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConnectHostgroupToNetworkInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
