// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2016, 2017, 2018 Alexandre Biancalana <ale@biancalanas.net>.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of the <organization> nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

package hostgroup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// FindComponentHostgroupsOKCode is the HTTP code returned for type FindComponentHostgroupsOK
const FindComponentHostgroupsOKCode int = 200

/*FindComponentHostgroupsOK successful operation

swagger:response findComponentHostgroupsOK
*/
type FindComponentHostgroupsOK struct {

	/*
	  In: Body
	*/
	Payload models.FindComponentHostgroupsOKBody `json:"body,omitempty"`
}

// NewFindComponentHostgroupsOK creates FindComponentHostgroupsOK with default headers values
func NewFindComponentHostgroupsOK() *FindComponentHostgroupsOK {
	return &FindComponentHostgroupsOK{}
}

// WithPayload adds the payload to the find component hostgroups o k response
func (o *FindComponentHostgroupsOK) WithPayload(payload models.FindComponentHostgroupsOKBody) *FindComponentHostgroupsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find component hostgroups o k response
func (o *FindComponentHostgroupsOK) SetPayload(payload models.FindComponentHostgroupsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindComponentHostgroupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.FindComponentHostgroupsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// FindComponentHostgroupsBadRequestCode is the HTTP code returned for type FindComponentHostgroupsBadRequest
const FindComponentHostgroupsBadRequestCode int = 400

/*FindComponentHostgroupsBadRequest Invalid cell id or component id

swagger:response findComponentHostgroupsBadRequest
*/
type FindComponentHostgroupsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewFindComponentHostgroupsBadRequest creates FindComponentHostgroupsBadRequest with default headers values
func NewFindComponentHostgroupsBadRequest() *FindComponentHostgroupsBadRequest {
	return &FindComponentHostgroupsBadRequest{}
}

// WithPayload adds the payload to the find component hostgroups bad request response
func (o *FindComponentHostgroupsBadRequest) WithPayload(payload *models.APIResponse) *FindComponentHostgroupsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find component hostgroups bad request response
func (o *FindComponentHostgroupsBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindComponentHostgroupsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindComponentHostgroupsInternalServerErrorCode is the HTTP code returned for type FindComponentHostgroupsInternalServerError
const FindComponentHostgroupsInternalServerErrorCode int = 500

/*FindComponentHostgroupsInternalServerError Internal error

swagger:response findComponentHostgroupsInternalServerError
*/
type FindComponentHostgroupsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewFindComponentHostgroupsInternalServerError creates FindComponentHostgroupsInternalServerError with default headers values
func NewFindComponentHostgroupsInternalServerError() *FindComponentHostgroupsInternalServerError {
	return &FindComponentHostgroupsInternalServerError{}
}

// WithPayload adds the payload to the find component hostgroups internal server error response
func (o *FindComponentHostgroupsInternalServerError) WithPayload(payload *models.APIResponse) *FindComponentHostgroupsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find component hostgroups internal server error response
func (o *FindComponentHostgroupsInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindComponentHostgroupsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
