// Code generated by go-swagger; DO NOT EDIT.

package hostgroup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// GetComponentHostgroupByIDOKCode is the HTTP code returned for type GetComponentHostgroupByIDOK
const GetComponentHostgroupByIDOKCode int = 200

/*GetComponentHostgroupByIDOK successful operation

swagger:response getComponentHostgroupByIdOK
*/
type GetComponentHostgroupByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Hostgroup `json:"body,omitempty"`
}

// NewGetComponentHostgroupByIDOK creates GetComponentHostgroupByIDOK with default headers values
func NewGetComponentHostgroupByIDOK() *GetComponentHostgroupByIDOK {
	return &GetComponentHostgroupByIDOK{}
}

// WithPayload adds the payload to the get component hostgroup by Id o k response
func (o *GetComponentHostgroupByIDOK) WithPayload(payload *models.Hostgroup) *GetComponentHostgroupByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get component hostgroup by Id o k response
func (o *GetComponentHostgroupByIDOK) SetPayload(payload *models.Hostgroup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetComponentHostgroupByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetComponentHostgroupByIDBadRequestCode is the HTTP code returned for type GetComponentHostgroupByIDBadRequest
const GetComponentHostgroupByIDBadRequestCode int = 400

/*GetComponentHostgroupByIDBadRequest Invalid cell id or component id

swagger:response getComponentHostgroupByIdBadRequest
*/
type GetComponentHostgroupByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewGetComponentHostgroupByIDBadRequest creates GetComponentHostgroupByIDBadRequest with default headers values
func NewGetComponentHostgroupByIDBadRequest() *GetComponentHostgroupByIDBadRequest {
	return &GetComponentHostgroupByIDBadRequest{}
}

// WithPayload adds the payload to the get component hostgroup by Id bad request response
func (o *GetComponentHostgroupByIDBadRequest) WithPayload(payload models.APIResponse) *GetComponentHostgroupByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get component hostgroup by Id bad request response
func (o *GetComponentHostgroupByIDBadRequest) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetComponentHostgroupByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetComponentHostgroupByIDNotFoundCode is the HTTP code returned for type GetComponentHostgroupByIDNotFound
const GetComponentHostgroupByIDNotFoundCode int = 404

/*GetComponentHostgroupByIDNotFound hostgroup does not exists

swagger:response getComponentHostgroupByIdNotFound
*/
type GetComponentHostgroupByIDNotFound struct {
}

// NewGetComponentHostgroupByIDNotFound creates GetComponentHostgroupByIDNotFound with default headers values
func NewGetComponentHostgroupByIDNotFound() *GetComponentHostgroupByIDNotFound {
	return &GetComponentHostgroupByIDNotFound{}
}

// WriteResponse to the client
func (o *GetComponentHostgroupByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetComponentHostgroupByIDInternalServerErrorCode is the HTTP code returned for type GetComponentHostgroupByIDInternalServerError
const GetComponentHostgroupByIDInternalServerErrorCode int = 500

/*GetComponentHostgroupByIDInternalServerError Internal error

swagger:response getComponentHostgroupByIdInternalServerError
*/
type GetComponentHostgroupByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewGetComponentHostgroupByIDInternalServerError creates GetComponentHostgroupByIDInternalServerError with default headers values
func NewGetComponentHostgroupByIDInternalServerError() *GetComponentHostgroupByIDInternalServerError {
	return &GetComponentHostgroupByIDInternalServerError{}
}

// WithPayload adds the payload to the get component hostgroup by Id internal server error response
func (o *GetComponentHostgroupByIDInternalServerError) WithPayload(payload models.APIResponse) *GetComponentHostgroupByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get component hostgroup by Id internal server error response
func (o *GetComponentHostgroupByIDInternalServerError) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetComponentHostgroupByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
