package hostgroup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"../../../models"
)

// UpdateComponentHostgroupHandlerFunc turns a function with the right signature into a update component hostgroup handler
type UpdateComponentHostgroupHandlerFunc func(UpdateComponentHostgroupParams, *models.Customer) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateComponentHostgroupHandlerFunc) Handle(params UpdateComponentHostgroupParams, principal *models.Customer) middleware.Responder {
	return fn(params, principal)
}

// UpdateComponentHostgroupHandler interface for that can handle valid update component hostgroup params
type UpdateComponentHostgroupHandler interface {
	Handle(UpdateComponentHostgroupParams, *models.Customer) middleware.Responder
}

// NewUpdateComponentHostgroup creates a new http.Handler for the update component hostgroup operation
func NewUpdateComponentHostgroup(ctx *middleware.Context, handler UpdateComponentHostgroupHandler) *UpdateComponentHostgroup {
	return &UpdateComponentHostgroup{Context: ctx, Handler: handler}
}

/*UpdateComponentHostgroup swagger:route PUT /cell/{cell_id}/component/{component_id}/hostgroup/{hostgroup_id} hostgroup updateComponentHostgroup

Update an existing hostgroup

*/
type UpdateComponentHostgroup struct {
	Context *middleware.Context
	Handler UpdateComponentHostgroupHandler
}

func (o *UpdateComponentHostgroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateComponentHostgroupParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Customer
	if uprinc != nil {
		principal = uprinc.(*models.Customer) // this is really a models.Customer, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
