// Code generated by go-swagger; DO NOT EDIT.

package hostgroup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"configManager/models"
)

// UpdateComponentHostgroupOKCode is the HTTP code returned for type UpdateComponentHostgroupOK
const UpdateComponentHostgroupOKCode int = 200

/*UpdateComponentHostgroupOK successful operation

swagger:response updateComponentHostgroupOK
*/
type UpdateComponentHostgroupOK struct {
}

// NewUpdateComponentHostgroupOK creates UpdateComponentHostgroupOK with default headers values
func NewUpdateComponentHostgroupOK() *UpdateComponentHostgroupOK {
	return &UpdateComponentHostgroupOK{}
}

// WriteResponse to the client
func (o *UpdateComponentHostgroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateComponentHostgroupBadRequestCode is the HTTP code returned for type UpdateComponentHostgroupBadRequest
const UpdateComponentHostgroupBadRequestCode int = 400

/*UpdateComponentHostgroupBadRequest Invalid cell id or role id

swagger:response updateComponentHostgroupBadRequest
*/
type UpdateComponentHostgroupBadRequest struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewUpdateComponentHostgroupBadRequest creates UpdateComponentHostgroupBadRequest with default headers values
func NewUpdateComponentHostgroupBadRequest() *UpdateComponentHostgroupBadRequest {
	return &UpdateComponentHostgroupBadRequest{}
}

// WithPayload adds the payload to the update component hostgroup bad request response
func (o *UpdateComponentHostgroupBadRequest) WithPayload(payload models.APIResponse) *UpdateComponentHostgroupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update component hostgroup bad request response
func (o *UpdateComponentHostgroupBadRequest) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateComponentHostgroupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateComponentHostgroupNotFoundCode is the HTTP code returned for type UpdateComponentHostgroupNotFound
const UpdateComponentHostgroupNotFoundCode int = 404

/*UpdateComponentHostgroupNotFound Hostgroup does not exists

swagger:response updateComponentHostgroupNotFound
*/
type UpdateComponentHostgroupNotFound struct {
}

// NewUpdateComponentHostgroupNotFound creates UpdateComponentHostgroupNotFound with default headers values
func NewUpdateComponentHostgroupNotFound() *UpdateComponentHostgroupNotFound {
	return &UpdateComponentHostgroupNotFound{}
}

// WriteResponse to the client
func (o *UpdateComponentHostgroupNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateComponentHostgroupInternalServerErrorCode is the HTTP code returned for type UpdateComponentHostgroupInternalServerError
const UpdateComponentHostgroupInternalServerErrorCode int = 500

/*UpdateComponentHostgroupInternalServerError Internal error

swagger:response updateComponentHostgroupInternalServerError
*/
type UpdateComponentHostgroupInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewUpdateComponentHostgroupInternalServerError creates UpdateComponentHostgroupInternalServerError with default headers values
func NewUpdateComponentHostgroupInternalServerError() *UpdateComponentHostgroupInternalServerError {
	return &UpdateComponentHostgroupInternalServerError{}
}

// WithPayload adds the payload to the update component hostgroup internal server error response
func (o *UpdateComponentHostgroupInternalServerError) WithPayload(payload models.APIResponse) *UpdateComponentHostgroupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update component hostgroup internal server error response
func (o *UpdateComponentHostgroupInternalServerError) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateComponentHostgroupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
