// Code generated by go-swagger; DO NOT EDIT.

package hostgroup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"configManager/models"
)

// NewUpdateComponentHostgroupParams creates a new UpdateComponentHostgroupParams object
// with the default values initialized.
func NewUpdateComponentHostgroupParams() UpdateComponentHostgroupParams {
	var ()
	return UpdateComponentHostgroupParams{}
}

// UpdateComponentHostgroupParams contains all the bound params for the update component hostgroup operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateComponentHostgroup
type UpdateComponentHostgroupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Hostgroup object that needs to be updated
	  Required: true
	  In: body
	*/
	Body *models.Hostgroup
	/*ID of cell that will be used
	  Required: true
	  In: path
	*/
	CellID int64
	/*ID of component that will be used
	  Required: true
	  In: path
	*/
	ComponentID int64
	/*hostgroup that will be updated
	  Required: true
	  In: path
	*/
	HostgroupID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *UpdateComponentHostgroupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Hostgroup
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	} else {
		res = append(res, errors.Required("body", "body"))
	}

	rCellID, rhkCellID, _ := route.Params.GetOK("cell_id")
	if err := o.bindCellID(rCellID, rhkCellID, route.Formats); err != nil {
		res = append(res, err)
	}

	rComponentID, rhkComponentID, _ := route.Params.GetOK("component_id")
	if err := o.bindComponentID(rComponentID, rhkComponentID, route.Formats); err != nil {
		res = append(res, err)
	}

	rHostgroupID, rhkHostgroupID, _ := route.Params.GetOK("hostgroup_id")
	if err := o.bindHostgroupID(rHostgroupID, rhkHostgroupID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateComponentHostgroupParams) bindCellID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("cell_id", "path", "int64", raw)
	}
	o.CellID = value

	return nil
}

func (o *UpdateComponentHostgroupParams) bindComponentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("component_id", "path", "int64", raw)
	}
	o.ComponentID = value

	return nil
}

func (o *UpdateComponentHostgroupParams) bindHostgroupID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("hostgroup_id", "path", "int64", raw)
	}
	o.HostgroupID = value

	return nil
}
