// Code generated by go-swagger; DO NOT EDIT.

package providertype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteProviderTypeBadRequestCode is the HTTP code returned for type DeleteProviderTypeBadRequest
const DeleteProviderTypeBadRequestCode int = 400

/*DeleteProviderTypeBadRequest Invalid ID supplied

swagger:response deleteProviderTypeBadRequest
*/
type DeleteProviderTypeBadRequest struct {
}

// NewDeleteProviderTypeBadRequest creates DeleteProviderTypeBadRequest with default headers values
func NewDeleteProviderTypeBadRequest() *DeleteProviderTypeBadRequest {
	return &DeleteProviderTypeBadRequest{}
}

// WriteResponse to the client
func (o *DeleteProviderTypeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteProviderTypeNotFoundCode is the HTTP code returned for type DeleteProviderTypeNotFound
const DeleteProviderTypeNotFoundCode int = 404

/*DeleteProviderTypeNotFound Provider not found

swagger:response deleteProviderTypeNotFound
*/
type DeleteProviderTypeNotFound struct {
}

// NewDeleteProviderTypeNotFound creates DeleteProviderTypeNotFound with default headers values
func NewDeleteProviderTypeNotFound() *DeleteProviderTypeNotFound {
	return &DeleteProviderTypeNotFound{}
}

// WriteResponse to the client
func (o *DeleteProviderTypeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
