package providertype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetProviderTypeByIDHandlerFunc turns a function with the right signature into a get provider type by Id handler
type GetProviderTypeByIDHandlerFunc func(GetProviderTypeByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProviderTypeByIDHandlerFunc) Handle(params GetProviderTypeByIDParams) middleware.Responder {
	return fn(params)
}

// GetProviderTypeByIDHandler interface for that can handle valid get provider type by Id params
type GetProviderTypeByIDHandler interface {
	Handle(GetProviderTypeByIDParams) middleware.Responder
}

// NewGetProviderTypeByID creates a new http.Handler for the get provider type by Id operation
func NewGetProviderTypeByID(ctx *middleware.Context, handler GetProviderTypeByIDHandler) *GetProviderTypeByID {
	return &GetProviderTypeByID{Context: ctx, Handler: handler}
}

/*GetProviderTypeByID swagger:route GET /providertype/{providertype_id} providertype getProviderTypeById

Find provider type by ID

Returns a single provider type

*/
type GetProviderTypeByID struct {
	Context *middleware.Context
	Handler GetProviderTypeByIDHandler
}

func (o *GetProviderTypeByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProviderTypeByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
