package providertype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../../models"
)

// ListProviderTypesOKCode is the HTTP code returned for type ListProviderTypesOK
const ListProviderTypesOKCode int = 200

/*ListProviderTypesOK successful operation

swagger:response listProviderTypesOK
*/
type ListProviderTypesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ProviderType `json:"body,omitempty"`
}

// NewListProviderTypesOK creates ListProviderTypesOK with default headers values
func NewListProviderTypesOK() *ListProviderTypesOK {
	return &ListProviderTypesOK{}
}

// WithPayload adds the payload to the list provider types o k response
func (o *ListProviderTypesOK) WithPayload(payload []*models.ProviderType) *ListProviderTypesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list provider types o k response
func (o *ListProviderTypesOK) SetPayload(payload []*models.ProviderType) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProviderTypesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.ProviderType, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ListProviderTypesInternalServerErrorCode is the HTTP code returned for type ListProviderTypesInternalServerError
const ListProviderTypesInternalServerErrorCode int = 500

/*ListProviderTypesInternalServerError InternalError

swagger:response listProviderTypesInternalServerError
*/
type ListProviderTypesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewListProviderTypesInternalServerError creates ListProviderTypesInternalServerError with default headers values
func NewListProviderTypesInternalServerError() *ListProviderTypesInternalServerError {
	return &ListProviderTypesInternalServerError{}
}

// WithPayload adds the payload to the list provider types internal server error response
func (o *ListProviderTypesInternalServerError) WithPayload(payload models.APIResponse) *ListProviderTypesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list provider types internal server error response
func (o *ListProviderTypesInternalServerError) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProviderTypesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
