// Code generated by go-swagger; DO NOT EDIT.

package providertype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateProviderTypeCreatedCode is the HTTP code returned for type UpdateProviderTypeCreated
const UpdateProviderTypeCreatedCode int = 201

/*UpdateProviderTypeCreated Created

swagger:response updateProviderTypeCreated
*/
type UpdateProviderTypeCreated struct {
}

// NewUpdateProviderTypeCreated creates UpdateProviderTypeCreated with default headers values
func NewUpdateProviderTypeCreated() *UpdateProviderTypeCreated {
	return &UpdateProviderTypeCreated{}
}

// WriteResponse to the client
func (o *UpdateProviderTypeCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// UpdateProviderTypeBadRequestCode is the HTTP code returned for type UpdateProviderTypeBadRequest
const UpdateProviderTypeBadRequestCode int = 400

/*UpdateProviderTypeBadRequest Invalid ID supplied

swagger:response updateProviderTypeBadRequest
*/
type UpdateProviderTypeBadRequest struct {
}

// NewUpdateProviderTypeBadRequest creates UpdateProviderTypeBadRequest with default headers values
func NewUpdateProviderTypeBadRequest() *UpdateProviderTypeBadRequest {
	return &UpdateProviderTypeBadRequest{}
}

// WriteResponse to the client
func (o *UpdateProviderTypeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateProviderTypeNotFoundCode is the HTTP code returned for type UpdateProviderTypeNotFound
const UpdateProviderTypeNotFoundCode int = 404

/*UpdateProviderTypeNotFound ProviderType not found

swagger:response updateProviderTypeNotFound
*/
type UpdateProviderTypeNotFound struct {
}

// NewUpdateProviderTypeNotFound creates UpdateProviderTypeNotFound with default headers values
func NewUpdateProviderTypeNotFound() *UpdateProviderTypeNotFound {
	return &UpdateProviderTypeNotFound{}
}

// WriteResponse to the client
func (o *UpdateProviderTypeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateProviderTypeMethodNotAllowedCode is the HTTP code returned for type UpdateProviderTypeMethodNotAllowed
const UpdateProviderTypeMethodNotAllowedCode int = 405

/*UpdateProviderTypeMethodNotAllowed Validation exception

swagger:response updateProviderTypeMethodNotAllowed
*/
type UpdateProviderTypeMethodNotAllowed struct {
}

// NewUpdateProviderTypeMethodNotAllowed creates UpdateProviderTypeMethodNotAllowed with default headers values
func NewUpdateProviderTypeMethodNotAllowed() *UpdateProviderTypeMethodNotAllowed {
	return &UpdateProviderTypeMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdateProviderTypeMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
