package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../../models"
)

// UpdateComponentRoleOKCode is the HTTP code returned for type UpdateComponentRoleOK
const UpdateComponentRoleOKCode int = 200

/*UpdateComponentRoleOK successful operation

swagger:response updateComponentRoleOK
*/
type UpdateComponentRoleOK struct {
}

// NewUpdateComponentRoleOK creates UpdateComponentRoleOK with default headers values
func NewUpdateComponentRoleOK() *UpdateComponentRoleOK {
	return &UpdateComponentRoleOK{}
}

// WriteResponse to the client
func (o *UpdateComponentRoleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// UpdateComponentRoleBadRequestCode is the HTTP code returned for type UpdateComponentRoleBadRequest
const UpdateComponentRoleBadRequestCode int = 400

/*UpdateComponentRoleBadRequest Invalid cell id or role id

swagger:response updateComponentRoleBadRequest
*/
type UpdateComponentRoleBadRequest struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewUpdateComponentRoleBadRequest creates UpdateComponentRoleBadRequest with default headers values
func NewUpdateComponentRoleBadRequest() *UpdateComponentRoleBadRequest {
	return &UpdateComponentRoleBadRequest{}
}

// WithPayload adds the payload to the update component role bad request response
func (o *UpdateComponentRoleBadRequest) WithPayload(payload models.APIResponse) *UpdateComponentRoleBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update component role bad request response
func (o *UpdateComponentRoleBadRequest) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateComponentRoleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// UpdateComponentRoleNotFoundCode is the HTTP code returned for type UpdateComponentRoleNotFound
const UpdateComponentRoleNotFoundCode int = 404

/*UpdateComponentRoleNotFound Role does not exists

swagger:response updateComponentRoleNotFound
*/
type UpdateComponentRoleNotFound struct {
}

// NewUpdateComponentRoleNotFound creates UpdateComponentRoleNotFound with default headers values
func NewUpdateComponentRoleNotFound() *UpdateComponentRoleNotFound {
	return &UpdateComponentRoleNotFound{}
}

// WriteResponse to the client
func (o *UpdateComponentRoleNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

// UpdateComponentRoleConflictCode is the HTTP code returned for type UpdateComponentRoleConflict
const UpdateComponentRoleConflictCode int = 409

/*UpdateComponentRoleConflict Role does not exists

swagger:response updateComponentRoleConflict
*/
type UpdateComponentRoleConflict struct {
}

// NewUpdateComponentRoleConflict creates UpdateComponentRoleConflict with default headers values
func NewUpdateComponentRoleConflict() *UpdateComponentRoleConflict {
	return &UpdateComponentRoleConflict{}
}

// WriteResponse to the client
func (o *UpdateComponentRoleConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}

// UpdateComponentRoleInternalServerErrorCode is the HTTP code returned for type UpdateComponentRoleInternalServerError
const UpdateComponentRoleInternalServerErrorCode int = 500

/*UpdateComponentRoleInternalServerError Internal error

swagger:response updateComponentRoleInternalServerError
*/
type UpdateComponentRoleInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.APIResponse `json:"body,omitempty"`
}

// NewUpdateComponentRoleInternalServerError creates UpdateComponentRoleInternalServerError with default headers values
func NewUpdateComponentRoleInternalServerError() *UpdateComponentRoleInternalServerError {
	return &UpdateComponentRoleInternalServerError{}
}

// WithPayload adds the payload to the update component role internal server error response
func (o *UpdateComponentRoleInternalServerError) WithPayload(payload models.APIResponse) *UpdateComponentRoleInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update component role internal server error response
func (o *UpdateComponentRoleInternalServerError) SetPayload(payload models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateComponentRoleInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
