package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../../models"
)

// FindCustomerByNameOKCode is the HTTP code returned for type FindCustomerByNameOK
const FindCustomerByNameOKCode int = 200

/*FindCustomerByNameOK successful operation

swagger:response findCustomerByNameOK
*/
type FindCustomerByNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Customer `json:"body,omitempty"`
}

// NewFindCustomerByNameOK creates FindCustomerByNameOK with default headers values
func NewFindCustomerByNameOK() *FindCustomerByNameOK {
	return &FindCustomerByNameOK{}
}

// WithPayload adds the payload to the find customer by name o k response
func (o *FindCustomerByNameOK) WithPayload(payload *models.Customer) *FindCustomerByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find customer by name o k response
func (o *FindCustomerByNameOK) SetPayload(payload *models.Customer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindCustomerByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindCustomerByNameBadRequestCode is the HTTP code returned for type FindCustomerByNameBadRequest
const FindCustomerByNameBadRequestCode int = 400

/*FindCustomerByNameBadRequest Invalid customer name

swagger:response findCustomerByNameBadRequest
*/
type FindCustomerByNameBadRequest struct {
}

// NewFindCustomerByNameBadRequest creates FindCustomerByNameBadRequest with default headers values
func NewFindCustomerByNameBadRequest() *FindCustomerByNameBadRequest {
	return &FindCustomerByNameBadRequest{}
}

// WriteResponse to the client
func (o *FindCustomerByNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// FindCustomerByNameNotFoundCode is the HTTP code returned for type FindCustomerByNameNotFound
const FindCustomerByNameNotFoundCode int = 404

/*FindCustomerByNameNotFound Customer not found

swagger:response findCustomerByNameNotFound
*/
type FindCustomerByNameNotFound struct {
}

// NewFindCustomerByNameNotFound creates FindCustomerByNameNotFound with default headers values
func NewFindCustomerByNameNotFound() *FindCustomerByNameNotFound {
	return &FindCustomerByNameNotFound{}
}

// WriteResponse to the client
func (o *FindCustomerByNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
