// Code generated by go-swagger; DO NOT EDIT.

package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindCustomerByNameParams creates a new FindCustomerByNameParams object
// with the default values initialized.
func NewFindCustomerByNameParams() FindCustomerByNameParams {
	var ()
	return FindCustomerByNameParams{}
}

// FindCustomerByNameParams contains all the bound params for the find customer by name operation
// typically these are obtained from a http.Request
//
// swagger:parameters findCustomerByName
type FindCustomerByNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name that need to be considered for filter
	  Required: true
	  In: query
	*/
	CustomerName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindCustomerByNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCustomerName, qhkCustomerName, _ := qs.GetOK("customer_name")
	if err := o.bindCustomerName(qCustomerName, qhkCustomerName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindCustomerByNameParams) bindCustomerName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("customer_name", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("customer_name", "query", raw); err != nil {
		return err
	}

	o.CustomerName = raw

	return nil
}
