package customer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"../../../models"
)

// GetCustomerByIDOKCode is the HTTP code returned for type GetCustomerByIDOK
const GetCustomerByIDOKCode int = 200

/*GetCustomerByIDOK successful operation

swagger:response getCustomerByIdOK
*/
type GetCustomerByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Customer `json:"body,omitempty"`
}

// NewGetCustomerByIDOK creates GetCustomerByIDOK with default headers values
func NewGetCustomerByIDOK() *GetCustomerByIDOK {
	return &GetCustomerByIDOK{}
}

// WithPayload adds the payload to the get customer by Id o k response
func (o *GetCustomerByIDOK) WithPayload(payload *models.Customer) *GetCustomerByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get customer by Id o k response
func (o *GetCustomerByIDOK) SetPayload(payload *models.Customer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCustomerByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCustomerByIDBadRequestCode is the HTTP code returned for type GetCustomerByIDBadRequest
const GetCustomerByIDBadRequestCode int = 400

/*GetCustomerByIDBadRequest Invalid ID supplied

swagger:response getCustomerByIdBadRequest
*/
type GetCustomerByIDBadRequest struct {
}

// NewGetCustomerByIDBadRequest creates GetCustomerByIDBadRequest with default headers values
func NewGetCustomerByIDBadRequest() *GetCustomerByIDBadRequest {
	return &GetCustomerByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetCustomerByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// GetCustomerByIDNotFoundCode is the HTTP code returned for type GetCustomerByIDNotFound
const GetCustomerByIDNotFoundCode int = 404

/*GetCustomerByIDNotFound Customer not found

swagger:response getCustomerByIdNotFound
*/
type GetCustomerByIDNotFound struct {
}

// NewGetCustomerByIDNotFound creates GetCustomerByIDNotFound with default headers values
func NewGetCustomerByIDNotFound() *GetCustomerByIDNotFound {
	return &GetCustomerByIDNotFound{}
}

// WriteResponse to the client
func (o *GetCustomerByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
